if("${CMAKE_FIND_ROOT_PATH}" STREQUAL "")
	set(Ox_INCLUDE_DIRS /usr/local/include/)
	set(OxStd_LIBRARY /usr/local/lib/ox/libOxStd.a)
	set(OxFS_LIBRARY /usr/local/lib/ox/libOxFS.a)
	set(OxClArgs_LIBRARY /usr/local/lib/ox/libOxClArgs.a)
	set(OxMetalClaw /usr/local/lib/ox/libOxMetalClaw.a)
else("${CMAKE_FIND_ROOT_PATH}" STREQUAL "")
	set(Ox_INCLUDE_DIRS ${CMAKE_FIND_ROOT_PATH}/include/)
	set(OxStd_LIBRARY ${CMAKE_FIND_ROOT_PATH}/lib/ox/libOxStd.a)
	set(OxFS_LIBRARY ${CMAKE_FIND_ROOT_PATH}/lib/ox/libOxFS.a)
	set(OxMetalClaw ${CMAKE_FIND_ROOT_PATH}/lib/ox/libOxMetalClaw.a)
endif("${CMAKE_FIND_ROOT_PATH}" STREQUAL "")
