if("${CMAKE_FIND_ROOT_PATH}" STREQUAL "")
	set(Ox_INCLUDE_DIRS /usr/local/include/)
	set(OxStd_LIBRARY /usr/local/lib/ox/libOxStd.a)
	set(OxFs_LIBRARY /usr/local/lib/ox/libOxFs.a)
else("${CMAKE_FIND_ROOT_PATH}" STREQUAL "")
	set(Ox_INCLUDE_DIRS ${CMAKE_FIND_ROOT_PATH}/include/)
	set(OxStd_LIBRARY ${CMAKE_FIND_ROOT_PATH}/lib/ox/libOxStd.a)
	set(OxFs_LIBRARY ${CMAKE_FIND_ROOT_PATH}/lib/ox/libOxFs.a)
endif("${CMAKE_FIND_ROOT_PATH}" STREQUAL "")
