#! /usr/bin/env bash

set -e

OS=$(uname | tr [:upper:] [:lower:])
TARGET=$OS-$(uname -m)

./scripts/setup_build $TARGET
./scripts/setup_build $TARGET debug
make -j -C build/${TARGET}-release all
make -j -C build/${TARGET}-release test
make -j -C build/${TARGET}-debug all
make -j -C build/${TARGET}-debug test
